# Generated by Django 5.1.4 on 2025-01-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.IntegerField()),
                ('account_status', models.CharField(max_length=50)),
                ('creditor_remark', models.TextField()),
                ('dispute_letter_generated', models.BooleanField(default=False)),
            ],
        ),
    ]
